#ifndef MESSAGING_GLOBAL_H
#define MESSAGING_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MESSAGING_LIBRARY)
#  define MESSAGINGSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MESSAGINGSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MESSAGING_GLOBAL_H
